title = "Moonpax"
baseURL = "https://example.com"
languageCode = "en"
theme = "ananke"
#themesDir = "../.."

commentoEnable = true
disqusShortname = "MOONPAX"

body_classes = "avenir bg-near-white"
custom_css = ["css/custom.css"]

DefaultContentLanguage = "en"
#copyright = "Everything is mine"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.he]
    languagedirection = "rtl"
    languageName = "עברית"
  [languages.en]
    languageName = "English"


[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  site_logo = ""
  description = "The last theme you'll ever need. Maybe."
  facebook = "https://www.facebook.com/moonpax"
  twitter = "https://twitter.com/GoHugoIO"
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black" #"bg-gray" #"bg-black" #"bg-blue"
  featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number = 2